version: '3.7'
services:
   database:
      image: postgres
      container_name: db_postgres
      restart: always
      environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: test
      ports:
        - "5433:5432"
